/**
 * FitLink Global — Affiliate Onboarding
 * data.js — Translations (T) + Partner data (PARTNERS)
 *
 * HOW TO ADD A NEW LANGUAGE:
 *   1. Duplicate the `en` block inside T and rename the key (e.g. `fr`)
 *   2. Add a new <button> in index.html lang switcher
 *   3. That's it — the app reads T[lang] automatically
 *
 * HOW TO ADD A NEW PARTNER:
 *   1. Add a new object to the correct category array in PARTNERS
 *      (hardware | software | services)
 *   2. Follow the existing object structure exactly
 *   3. The partner card and modal render automatically
 *
 * Last updated: 2025
 */

const T = {
  es: {
    welcome_badge:"BIENVENIDO AL EQUIPO",
    hero_line1:"Estás a punto de", hero_line2:"vender el futuro", hero_line3:"del fitness",
    hero_desc:"Este sistema te da todo lo que necesitas para representar a FitLink Global con autoridad, confianza y resultados. No es un catálogo &#8212; es una ventaja competitiva.",
    pill1:"20+ Partners", pill2:"4 Continentes", pill3:"Hardware · Software · Diseño",
    stat1:"Partners", stat2:"Países", stat3:"Oportunidad",
    scroll_hint:"Desliza para comenzar",
    story_tag:"LA HISTORIA", story_title:"No somos una distribuidora. Somos un ecosistema.",
    story_desc:"FitLink opera desde Berlín conectando los mejores productos del mundo fitness con operadores en DACH, España y Latinoamérica.",
    quote:"El fitness no es solo industria. Es el espejo donde la sociedad refleja sus valores de salud, longevidad y bienestar.",
    port_tag:"EL PORTFOLIO", port_title:"Cada producto, una oportunidad.",
    port_desc:"Toca cualquier partner para ver su ficha completa: productos destacados, argumentos de venta y combos recomendados.",
    port_note:"El portfolio crece constantemente. Los revendedores reciben acceso anticipado a nuevos lanzamientos.",
    strat_tag:"ESTRATEGIAS", strat_title:"No hay una sola forma de ganar. Hay cinco.",
    strat_desc:"Cada estrategia tiene su propio playbook. Toca para expandir.",
    road_tag:"TU CAMINO", road_title:"Los primeros 60 días lo cambian todo.",
    man_tag:"EL MANIFESTO", man_t1:"No eres un vendedor.", man_t2:"Eres un", man_t3:"arquitecto", man_t4:"de negocios fitness.",
    man_quote:"El mercado global de fitness y wellness supera los $5 billones. La ventana para posicionarse como referente ya está abierta.",
    mkt1:"Mercado Principal", mkt2:"Expansión Activa", mkt3:"Visión FitLink",
    cta_tag:"SIGUIENTE PASO", cta_ttl:"El onboarding termina. El trabajo empieza.",
    cta_dsc:"Vuelve a este sistema cuando necesites. Explora el portfolio, practica los argumentos de venta, y contáctanos con tu primer prospecto.",
    nav_prev:"← Anterior", nav_next:"Siguiente →",
    sec_names:["Bienvenida","La Historia","Portfolio","Estrategias","Tu Camino","Manifesto"],
    cat_hw:"Hardware", cat_sw:"Software", cat_sv:"Servicios",
    modal_desc:"DESCRIPCIÓN", modal_ideal:"CLIENTE IDEAL", modal_pitch:"ARGUMENTO DE VENTA",
    modal_prods:"PRODUCTOS DESTACADOS", modal_obj:"OBJECIONES COMUNES", modal_combo:"COMBO RECOMENDADO",
    swipe_hint:"Deslizá hacia arriba para ver más",
    tl:[
      {y:"EL ORIGEN",t:"Una brecha en el mercado",b:"FitLink nació de observar que el sector fitness global carecía de un puente real entre la innovación tecnológica y los operadores de negocio. Las mejores soluciones no llegaban a quienes más las necesitaban."},
      {y:"LA VISIÓN",t:"Más que distribución",b:"Desde el primer día, FitLink se posicionó como socio estratégico. No vendemos productos: conectamos soluciones con problemas reales y construimos relaciones de largo plazo."},
      {y:"LA RED",t:"20+ partners de primer nivel",b:"Un portfolio cuidadosamente seleccionado: hardware de vanguardia, software que genera datos accionables, y servicios que transforman espacios en experiencias."},
      {y:"HOY",t:"Donde tú entras",b:"FitLink opera en DACH, España y Latinoamérica con una red de revendedores que multiplica el impacto. Tu éxito es nuestro éxito."},
    ],
    strats:[
      {ico:"◆",ttl:"La Estrategia del Combo",sub:"Hardware + Software = Retención máxima",badge:"ALTO ROI",desc:"Nunca vendas solo hardware o solo software. El combo crea dependencia positiva y aumenta el ticket promedio 2&#8211;3×.",steps:["Identifica el pain principal del cliente","Propón el hardware que resuelve el problema visible","Añade el software que lo potencia y digitaliza","Presenta el ROI combinado como una sola inversión"],ex:"Wiemspro + Harbiz + Lemin = Centro EMS llave en mano"},
      {ico:"◆",ttl:"La Estrategia Vertical",sub:"Especialización por tipo de cliente",badge:"REFERIDOS",desc:"Domina un vertical antes de expandirte. La especialización genera referidos naturales y posicionamiento de autoridad.",steps:["Elige un vertical: fisioterapia, wellness, boutique, corporativo","Aprende el lenguaje específico del sector","Construye casos de éxito en ese vertical","Usa cada cliente como referencia para el siguiente"],ex:"Fisioterapia: BASI + CUBE Sports + SelfLoops = Solución clínica completa"},
      {ico:"◆",ttl:"La Estrategia Premium",sub:"Vende la experiencia, no el producto",badge:"TICKET ALTO",desc:"Los mejores clientes compran visión. Presenta FitLink como asesoría estratégica, no como distribuidora.",steps:["Abre con preguntas sobre el proyecto, no el presupuesto","Diseña propuesta a medida con 3&#8211;5 productos complementarios","Incluye siempre Mironova en proyectos de apertura","Negocia paquetes, nunca productos sueltos"],ex:"Hotel 5*: Sparkfield + ICAROS + POOLBIKING + Mironova = Wellness Experience única"},
      {ico:"◆",ttl:"La Estrategia SaaS First",sub:"Empieza con software, escala con hardware",badge:"LARGO PLAZO",desc:"El software entra fácil, crea relación, genera confianza. El hardware viene después.",steps:["Empieza con Harbiz o WizFit AI","Demuestra valor rápido con demo funcional","Identifica carencias del espacio físico","Propón equipamiento como upgrade natural"],ex:"Harbiz → WizFit AI → Bodytone = Relación de 3 años"},
      {ico:"◆",ttl:"La Estrategia de Urgencia",sub:"El mercado no espera",badge:"CIERRE RÁPIDO",desc:"Crea urgencia genuina con datos de mercado reales &#8212; no urgencia artificial.",steps:["Lleva datos: 'El mercado EMS crece X% anual en DACH'","Señala el costo de no decidir: competidores ya adoptaron","Propón un piloto de bajo riesgo","Define un deadline ligado a disponibilidad o precio"],ex:"ROOK: 'Tu competidor ya integra wearables. Cada mes sin datos es market share perdido'"},
    ],
    rm:[
      {d:"Día 1&#8211;3",ico:"◆",t:"Inmersión de Producto",b:"Conoce el portfolio completo. Identifica tus 3 productos favoritos para comenzar."},
      {d:"Día 4&#8211;7",ico:"◆",t:"Elige tu Vertical",b:"Decide en qué mercado quieres especializarte primero."},
      {d:"Semana 2",ico:"◆",t:"Primeros Contactos",b:"5 llamadas de exploración sin objetivo de venta. Solo escucha y aprende."},
      {d:"Semana 3",ico:"◆",t:"Primera Propuesta",b:"Prepara una propuesta combo para tu mejor prospecto."},
      {d:"Mes 2",ico:"◆",t:"Primer Cierre",b:"Con el pipeline activo, el primer cierre llega. El momentum empieza aquí."},
    ],
    princs:[
      {ico:"◆",t:"Especialización",d:"Un mercado primero. Profundidad antes que amplitud."},
      {ico:"◆",t:"Relación primero",d:"La confianza de hoy es la comisión de mañana."},
      {ico:"◆",t:"Habla con datos",d:"ROI y casos de éxito cierran puertas."},
      {ico:"◆",t:"Piensa en combos",d:"Dos productos juntos valen más que dos veces uno."},
    ],
    m_lines:["Cada gimnasio que equipas mejor mejora la vida de sus miembros.","Cada software que implementas convierte datos en decisiones más inteligentes.","Cada solución que recomiendas construye tu reputación como experto del sector.","Tu éxito y el éxito de tus clientes son la misma cosa."],
  },
  en: {
    welcome_badge:"WELCOME TO THE TEAM",
    hero_line1:"You're about to", hero_line2:"sell the future", hero_line3:"of fitness",
    hero_desc:"This system gives you everything you need to represent FitLink Global with authority, confidence, and results. Not a catalogue &#8212; a competitive edge.",
    pill1:"20+ Partners", pill2:"4 Continents", pill3:"Hardware · Software · Design",
    stat1:"Partners", stat2:"Countries", stat3:"Opportunity",
    scroll_hint:"Swipe to begin",
    story_tag:"THE STORY", story_title:"We're not a distributor. We're an ecosystem.",
    story_desc:"FitLink operates from Berlin connecting the world's best fitness products with operators across DACH, Spain and Latin America.",
    quote:"Fitness is not just an industry. It's the mirror where society reflects its values of health, longevity and wellbeing.",
    port_tag:"THE PORTFOLIO", port_title:"Every product, an opportunity.",
    port_desc:"Tap any partner to see the full profile: key products, sales arguments and recommended combos.",
    port_note:"The portfolio grows constantly. Resellers get early access to new product launches.",
    strat_tag:"SALES STRATEGIES", strat_title:"There's not one way to win. There are five.",
    strat_desc:"Each strategy has its own playbook. Tap to expand.",
    road_tag:"YOUR PATH", road_title:"The first 60 days change everything.",
    man_tag:"THE MANIFESTO", man_t1:"You're not a salesperson.", man_t2:"You're an", man_t3:"architect", man_t4:"of fitness businesses.",
    man_quote:"The global fitness & wellness market exceeds $5 trillion. The window to position yourself as a category leader is open right now.",
    mkt1:"Primary Market", mkt2:"Active Expansion", mkt3:"FitLink Vision",
    cta_tag:"NEXT STEP", cta_ttl:"Onboarding ends. Work begins.",
    cta_dsc:"Come back to this system whenever you need. Explore the portfolio, practice your sales arguments, and reach out when you have your first qualified prospect.",
    nav_prev:"← Previous", nav_next:"Next →",
    sec_names:["Welcome","The Story","Portfolio","Strategies","Your Path","Manifesto"],
    cat_hw:"Hardware", cat_sw:"Software", cat_sv:"Services",
    modal_desc:"DESCRIPTION", modal_ideal:"IDEAL CLIENT", modal_pitch:"YOUR SALES PITCH",
    modal_prods:"KEY PRODUCTS", modal_obj:"COMMON OBJECTIONS", modal_combo:"RECOMMENDED COMBO",
    swipe_hint:"Swipe up to see more",
    tl:[
      {y:"THE ORIGIN",t:"A gap in the market",b:"FitLink was born from observing that the global fitness sector lacked a real bridge between technological innovation and business operators. The best solutions weren't reaching those who needed them most."},
      {y:"THE VISION",t:"More than distribution",b:"From day one, FitLink positioned itself as a strategic partner. We don't sell products: we connect solutions with real problems and build long-term relationships."},
      {y:"THE NETWORK",t:"20+ first-class partners",b:"A carefully selected portfolio: cutting-edge hardware, software that generates actionable data, and services that transform spaces into experiences."},
      {y:"TODAY",t:"Where you come in",b:"FitLink operates in DACH, Spain and Latin America with a reseller network that multiplies impact. Your success is our success."},
    ],
    strats:[
      {ico:"◆",ttl:"The Combo Strategy",sub:"Hardware + Software = Maximum Retention",badge:"HIGH ROI",desc:"Never sell just hardware or just software. The combo creates positive dependency and increases average ticket 2&#8211;3×.",steps:["Identify the client's primary pain point","Propose the hardware that solves the visible problem","Add the software that powers and digitizes it","Present the combined ROI as a single investment"],ex:"Wiemspro + Harbiz + Lemin = Turnkey EMS Center"},
      {ico:"◆",ttl:"The Vertical Strategy",sub:"Specialization by client type",badge:"REFERRALS",desc:"Dominate one vertical before expanding. Specialization generates natural referrals and authority positioning.",steps:["Choose a vertical: physio, wellness, boutique, corporate","Learn the specific language of the sector","Build success cases in that vertical","Use each client as a reference for the next"],ex:"Physio: BASI + CUBE Sports + SelfLoops = Complete clinical solution"},
      {ico:"◆",ttl:"The Premium Strategy",sub:"Sell the experience, not the product",badge:"HIGH TICKET",desc:"The best clients buy vision. Present FitLink as strategic consulting, not a distributor.",steps:["Open with questions about the project, not the budget","Design a tailored proposal with 3&#8211;5 complementary products","Always include Mironova in opening projects","Negotiate packages, never individual products"],ex:"5* Hotel: Sparkfield + ICAROS + POOLBIKING + Mironova = Unique Wellness Experience"},
      {ico:"◆",ttl:"The SaaS First Strategy",sub:"Start with software, scale with hardware",badge:"LONG TERM",desc:"Software gets in easily, creates a relationship, builds trust. Hardware comes after.",steps:["Start with Harbiz or WizFit AI","Demonstrate value quickly with a functional demo","Identify physical space gaps during the process","Propose equipment as a natural upgrade"],ex:"Harbiz → WizFit AI → Bodytone = 3-year relationship"},
      {ico:"◆",ttl:"The Urgency Strategy",sub:"The market won't wait",badge:"FAST CLOSE",desc:"Create genuine urgency with real market data &#8212; not artificial pressure.",steps:["Bring data: 'The EMS market grows X% annually in DACH'","Highlight the cost of not deciding: competitors already adopted","Propose a low-risk pilot","Define a clear deadline tied to availability or price"],ex:"ROOK: 'Your competitor already integrates wearables. Every month without data is lost market share'"},
    ],
    rm:[
      {d:"Day 1&#8211;3",ico:"◆",t:"Product Immersion",b:"Learn the complete portfolio. Identify your 3 favourite products to start with."},
      {d:"Day 4&#8211;7",ico:"◆",t:"Choose Your Vertical",b:"Decide which market you want to specialise in first."},
      {d:"Week 2",ico:"◆",t:"First Contacts",b:"5 exploratory calls with no sales objective. Just listen and learn."},
      {d:"Week 3",ico:"◆",t:"First Proposal",b:"Prepare a combo proposal for your best prospect."},
      {d:"Month 2",ico:"◆",t:"First Close",b:"With an active pipeline, the first close arrives. Momentum starts here."},
    ],
    princs:[
      {ico:"◆",t:"Specialise",d:"One market first. Depth before breadth."},
      {ico:"◆",t:"Relationship first",d:"Today's trust is tomorrow's commission."},
      {ico:"◆",t:"Talk with data",d:"ROI and success cases close doors."},
      {ico:"◆",t:"Think in combos",d:"Two products together are worth more than two separate ones."},
    ],
    m_lines:["Every gym you equip better improves the lives of its members.","Every software you implement turns data into smarter decisions.","Every solution you recommend builds your reputation as a sector expert.","Your success and your clients' success are the same thing."],
  },
  de: {
    welcome_badge:"WILLKOMMEN IM TEAM",
    hero_line1:"Du stehst kurz davor,", hero_line2:"die Zukunft", hero_line3:"des Fitness zu verkaufen",
    hero_desc:"Dieses System gibt dir alles, was du brauchst, um FitLink Global mit Autorität, Vertrauen und Ergebnissen zu vertreten. Kein Katalog &#8212; ein Wettbewerbsvorteil.",
    pill1:"20+ Partner", pill2:"4 Kontinente", pill3:"Hardware · Software · Design",
    stat1:"Partner", stat2:"Länder", stat3:"Chance",
    scroll_hint:"Wischen zum Starten",
    story_tag:"DIE GESCHICHTE", story_title:"Wir sind kein Distributor. Wir sind ein Ökosystem.",
    story_desc:"FitLink operiert von Berlin aus und verbindet die besten Fitnessprodukte der Welt mit Betreibern in DACH, Spanien und Lateinamerika.",
    quote:"Fitness ist nicht nur eine Industrie. Es ist der Spiegel, in dem die Gesellschaft ihre Werte von Gesundheit, Langlebigkeit und Wohlbefinden widerspiegelt.",
    port_tag:"DAS PORTFOLIO", port_title:"Jedes Produkt, eine Chance.",
    port_desc:"Tippe auf einen Partner für das vollständige Profil: Schlüsselprodukte, Verkaufsargumente und empfohlene Kombinationen.",
    port_note:"Das Portfolio wächst ständig. Wiederverkäufer erhalten frühzeitigen Zugang zu neuen Produkten.",
    strat_tag:"VERKAUFSSTRATEGIEN", strat_title:"Es gibt nicht einen Weg zu gewinnen. Es gibt fünf.",
    strat_desc:"Jede Strategie hat ihr eigenes Playbook. Antippen zum Erweitern.",
    road_tag:"DEIN WEG", road_title:"Die ersten 60 Tage verändern alles.",
    man_tag:"DAS MANIFEST", man_t1:"Du bist kein Verkäufer.", man_t2:"Du bist ein", man_t3:"Architekt", man_t4:"von Fitnessunternehmen.",
    man_quote:"Der globale Fitness- und Wellnessmarkt überschreitet 5 Billionen Dollar. Das Fenster zur Positionierung als Marktführer steht jetzt offen.",
    mkt1:"Hauptmarkt", mkt2:"Aktive Expansion", mkt3:"FitLink Vision",
    cta_tag:"NÄCHSTER SCHRITT", cta_ttl:"Onboarding endet. Arbeit beginnt.",
    cta_dsc:"Komme wann immer nötig zurück. Erkunde das Portfolio, übe deine Verkaufsargumente und kontaktiere uns bei deinem ersten qualifizierten Lead.",
    nav_prev:"← Zurück", nav_next:"Weiter →",
    sec_names:["Willkommen","Die Geschichte","Portfolio","Strategien","Dein Weg","Manifest"],
    cat_hw:"Hardware", cat_sw:"Software", cat_sv:"Services",
    modal_desc:"BESCHREIBUNG", modal_ideal:"IDEALER KUNDE", modal_pitch:"DEIN VERKAUFSARGUMENT",
    modal_prods:"HAUPTPRODUKTE", modal_obj:"HÄUFIGE EINWÄNDE", modal_combo:"EMPFOHLENE KOMBINATION",
    swipe_hint:"Nach oben wischen für mehr",
    tl:[
      {y:"DER URSPRUNG",t:"Eine Marktlücke",b:"FitLink entstand aus der Beobachtung, dass dem globalen Fitnesssektor eine echte Brücke zwischen technologischer Innovation und Geschäftsbetreibern fehlte."},
      {y:"DIE VISION",t:"Mehr als Distribution",b:"Von Anfang an positionierte sich FitLink als strategischer Partner. Wir verkaufen keine Produkte: Wir verbinden Lösungen mit echten Problemen."},
      {y:"DAS NETZWERK",t:"20+ erstklassige Partner",b:"Ein sorgfältig ausgewähltes Portfolio: Spitzenhardware, Software die verwertbare Daten generiert, und Services die Räume in Erlebnisse verwandeln."},
      {y:"HEUTE",t:"Wo du einsteigst",b:"FitLink operiert in DACH, Spanien und Lateinamerika mit einem Händlernetz das die Wirkung multipliziert. Dein Erfolg ist unser Erfolg."},
    ],
    strats:[
      {ico:"◆",ttl:"Die Kombinations-Strategie",sub:"Hardware + Software = Maximale Bindung",badge:"HOHER ROI",desc:"Verkaufe nie nur Hardware oder nur Software. Die Kombination schafft positive Abhängigkeit und erhöht das Durchschnittsticket um das 2&#8211;3-Fache.",steps:["Identifiziere den Hauptschmerzpunkt des Kunden","Schlage die Hardware vor, die das sichtbare Problem löst","Füge die Software hinzu, die es potenziert","Präsentiere den kombinierten ROI als eine einzige Investition"],ex:"Wiemspro + Harbiz + Lemin = Schlüsselfertiges EMS-Center"},
      {ico:"◆",ttl:"Die Vertikal-Strategie",sub:"Spezialisierung nach Kundentyp",badge:"EMPFEHLUNGEN",desc:"Beherrsche eine Nische, bevor du expandierst. Spezialisierung erzeugt natürliche Weiterempfehlungen.",steps:["Wähle eine Nische: Physio, Wellness, Boutique, Corporate","Lerne die spezifische Sprache der Branche","Baue Erfolgsbeispiele in dieser Nische auf","Nutze jeden Kunden als Referenz für den nächsten"],ex:"Physiotherapie: BASI + CUBE Sports + SelfLoops = Vollständige Kliniiklösung"},
      {ico:"◆",ttl:"Die Premium-Strategie",sub:"Verkaufe das Erlebnis, nicht das Produkt",badge:"HOHES TICKET",desc:"Die besten Kunden kaufen eine Vision. Präsentiere FitLink als strategische Beratung.",steps:["Öffne mit Fragen zum Projekt, nicht zum Budget","Entwirf ein maßgeschneidertes Angebot mit 3&#8211;5 Produkten","Inkludiere immer Mironova bei Eröffnungsprojekten","Verhandle Pakete, niemals Einzelprodukte"],ex:"5*-Hotel: Sparkfield + ICAROS + POOLBIKING + Mironova = Einzigartiges Wellness-Erlebnis"},
      {ico:"◆",ttl:"Die SaaS-First-Strategie",sub:"Beginne mit Software, skaliere mit Hardware",badge:"LANGFRISTIG",desc:"Software kommt leicht rein, baut Beziehungen, schafft Vertrauen. Hardware folgt danach.",steps:["Beginne mit Harbiz oder WizFit AI","Zeige schnell Wert mit einer Demo","Identifiziere Lücken im physischen Bereich","Schlage Equipment als natürliches Upgrade vor"],ex:"Harbiz → WizFit AI → Bodytone = 3-Jahres-Beziehung"},
      {ico:"◆",ttl:"Die Dringlichkeits-Strategie",sub:"Der Markt wartet nicht",badge:"SCHNELLER ABSCHLUSS",desc:"Schaffe echte Dringlichkeit mit realen Marktdaten &#8212; kein künstlicher Druck.",steps:["Bring Daten: 'Der EMS-Markt wächst jährlich X% in DACH'","Zeige die Kosten des Nicht-Entscheidens auf","Schlage einen risikoarmen Piloten vor","Definiere eine klare Deadline"],ex:"ROOK: 'Dein Konkurrent integriert bereits Wearables. Jeder Monat ohne Daten ist verlorener Marktanteil'"},
    ],
    rm:[
      {d:"Tag 1&#8211;3",ico:"◆",t:"Produkt-Immersion",b:"Lerne das komplette Portfolio. Identifiziere deine 3 Lieblingsprodukte zum Starten."},
      {d:"Tag 4&#8211;7",ico:"◆",t:"Wähle deine Nische",b:"Entscheide, in welchem Markt du dich zuerst spezialisieren möchtest."},
      {d:"Woche 2",ico:"◆",t:"Erste Kontakte",b:"5 Erkundungsanrufe ohne Verkaufsziel. Nur zuhören und lernen."},
      {d:"Woche 3",ico:"◆",t:"Erster Vorschlag",b:"Bereite ein Kombiangebot für deinen besten Interessenten vor."},
      {d:"Monat 2",ico:"◆",t:"Erster Abschluss",b:"Mit aktivem Pipeline kommt der erste Abschluss. Der Schwung beginnt hier."},
    ],
    princs:[
      {ico:"◆",t:"Spezialisierung",d:"Ein Markt zuerst. Tiefe vor Breite."},
      {ico:"◆",t:"Beziehung zuerst",d:"Das heutige Vertrauen ist die morgige Provision."},
      {ico:"◆",t:"Mit Daten sprechen",d:"ROI und Erfolgsbeispiele schließen Türen."},
      {ico:"◆",t:"In Kombis denken",d:"Zwei Produkte zusammen sind mehr wert als zwei getrennte."},
    ],
    m_lines:["Jedes Fitnessstudio, das du besser ausstattest, verbessert das Leben seiner Mitglieder.","Jede Software, die du implementierst, verwandelt Daten in intelligentere Entscheidungen.","Jede Lösung, die du empfiehlst, baut deinen Ruf als Branchenexperte auf.","Dein Erfolg und der Erfolg deiner Kunden sind ein und dasselbe."],
  }
};

/* -----------------------------------------------
   PARTNER DATA (full, with products & objections)
----------------------------------------------- */
const PARTNERS = {
  hardware:[
    {
      id:"trackbar", emoji:"·", tag:"Performance Tracking",
      name:"Trackbar", tagline:"Machine digitization in real time",
      taglineEs:"Digitalización de máquinas en tiempo real",
      taglineDe:"Maschinendigitalisierung in Echtzeit",
      descEs:"Trackbar convierte cualquier máquina de gimnasio en un dispositivo inteligente. Registra métricas de entrenamiento en tiempo real y las convierte en datos accionables para el operador.",
      descEn:"Trackbar turns any gym machine into a smart device. It records training metrics in real time and converts them into actionable data for the operator.",
      descDe:"Trackbar verwandelt jede Fitnessmaschine in ein intelligentes Gerät. Es erfasst Trainingsmetriken in Echtzeit.",
      idealEs:["Gimnasios premium","Centros de alto rendimiento","Cadenas de fitness"],
      idealEn:["Premium gyms","High-performance centers","Fitness chains"],
      idealDe:["Premium-Studios","Hochleistungszentren","Fitnessketten"],
      pitchEs:"Tus miembros quieren datos. Trackbar los convierte en resultados visibles que fidelizan y diferencian.",
      pitchEn:"Your members want data. Trackbar turns them into visible results that build loyalty and differentiation.",
      pitchDe:"Deine Mitglieder wollen Daten. Trackbar verwandelt sie in sichtbare Ergebnisse.",
      products:[
        {ico:"◆",name:"Trackbar Sensor",desc:"Sensor universal adaptable a cualquier máquina. Instalación en minutos."},
        {ico:"◆",name:"Trackbar App",desc:"Dashboard en tiempo real para miembros y operadores."},
        {ico:"◆",name:"Trackbar Analytics",desc:"Informes avanzados de uso, rendimiento y retención."},
      ],
      objEs:[{q:"'Ya tenemos nuestro sistema de gestión'",a:"Trackbar no reemplaza tu gestión &#8212; se integra con ella y añade la capa de datos de uso de máquinas que ningún otro sistema tiene."}],
      comboEs:"Trackbar + SelfLoops + Harbiz = El gimnasio más orientado a datos de tu ciudad",
    },
    {
      id:"mindzmove", emoji:"·", tag:"Neuro-Fitness",
      name:"Mindzmove", tagline:"Where movement meets the mind",
      taglineEs:"Donde el movimiento se encuentra con la mente",
      taglineDe:"Wo Bewegung auf den Geist trifft",
      descEs:"Tecnología que une el entrenamiento físico con el bienestar cognitivo y emocional. Diferenciador poderoso para centros de wellness de alto valor.",
      descEn:"Technology that unites physical training with cognitive and emotional wellbeing. A powerful differentiator for high-value wellness centers.",
      descDe:"Technologie die körperliches Training mit kognitivem und emotionalem Wohlbefinden verbindet.",
      idealEs:["Wellness centers","Clínicas de salud","Spas corporativos"],
      idealEn:["Wellness centers","Health clinics","Corporate spas"],
      idealDe:["Wellness-Center","Gesundheitskliniken","Unternehmens-Spas"],
      pitchEs:"El mercado del bienestar mental explota. Mindzmove es la puerta de entrada para operadores que quieren liderar esa tendencia.",
      pitchEn:"The mental wellness market is exploding. Mindzmove is the gateway for operators who want to lead that trend.",
      pitchDe:"Der Markt für mentales Wohlbefinden explodiert. Mindzmove ist das Eintrittstor.",
      products:[
        {ico:"◆",name:"Mindzmove Motion",desc:"Sistema de movimiento guiado con retroalimentación emocional en tiempo real."},
        {ico:"◆",name:"Mindzmove Breathe",desc:"Protocolo de respiración y movimiento para reducción del estrés."},
      ],
      objEs:[{q:"'Nuestros clientes vienen a entrenar, no a meditar'",a:"Mindzmove no es meditación &#8212; es una capa de bienestar que hace el entrenamiento más efectivo y reduce el abandono un 30%."}],
      comboEs:"Mindzmove + Sparkfield + Harbiz = Centro de bienestar mental-físico completo",
    },
    {
      id:"basi", emoji:"·", tag:"Pilates & Rehab",
      name:"BASI Systems", tagline:"The world standard in Pilates equipment",
      taglineEs:"El estándar mundial en equipamiento Pilates",
      taglineDe:"Der Weltstandard in Pilates-Equipment",
      descEs:"Equipamiento Pilates de gama alta con respaldo pedagógico y certificación internacional. Referente global en reformers y sistemas de rehabilitación con más de 30 años de historia.",
      descEn:"High-end Pilates equipment with pedagogical backing and international certification. Global reference in reformers and rehabilitation systems with over 30 years of history.",
      descDe:"Hochwertiges Pilates-Equipment mit pädagogischer Unterstützung und internationaler Zertifizierung.",
      idealEs:["Estudios Pilates","Clínicas fisioterapia","Centros médicos premium"],
      idealEn:["Pilates studios","Physiotherapy clinics","Premium medical centers"],
      idealDe:["Pilates-Studios","Physiotherapiekliniken","Premium-Medizinzentren"],
      pitchEs:"BASI es la marca que los instructores certificados exigen. Vender BASI es vender prestigio &#8212; el cliente ya lo conoce y lo quiere.",
      pitchEn:"BASI is the brand certified instructors demand. Selling BASI means selling prestige &#8212; clients already know and want it.",
      pitchDe:"BASI ist die Marke, die zertifizierte Instruktoren verlangen. BASI zu verkaufen bedeutet Prestige zu verkaufen.",
      products:[
        {ico:"◆",name:"BASI Reformer",desc:"El reformer más reconocido a nivel mundial. Múltiples configuraciones."},
        {ico:"◆",name:"BASI F2 System",desc:"Sistema de entrenamiento funcional integrado con filosofía Pilates."},
        {ico:"◆",name:"BASI Cadillac",desc:"Equipo de rehabilitación y entrenamiento avanzado. Estándar en clínicas de alto nivel."},
        {ico:"◆",name:"BASI Education",desc:"Programa de certificación internacional &#8212; añade valor y genera fidelidad."},
      ],
      objEs:[{q:"'Es demasiado caro para mis clientes'",a:"El cliente de BASI no busca precio &#8212; busca calidad certificada. Si tu cliente habla de precio, aún no es el cliente de BASI."}],
      comboEs:"BASI + Mironova + Harbiz = Estudio Pilates premium llave en mano",
    },
    {
      id:"wiemspro", emoji:"·", tag:"EMS Technology",
      name:"Wiemspro", tagline:"Elite EMS &#8212; results in 20 minutes",
      taglineEs:"EMS de élite &#8212; resultados en 20 minutos",
      taglineDe:"Elite-EMS &#8212; Ergebnisse in 20 Minuten",
      descEs:"Sistemas EMS profesionales inalámbricos presentes en 77 países con certificación FDA y CE. El modelo de negocio de menor espacio y mayor facturación por m² del sector.",
      descEn:"Professional wireless EMS systems present in 77 countries with FDA and CE certification. The fitness business model with the lowest space and highest revenue per m².",
      descDe:"Professionelle kabellose EMS-Systeme in 77 Ländern mit FDA- und CE-Zertifizierung.",
      idealEs:["Boutique fitness EMS","Franquicias","Personal trainers premium"],
      idealEn:["EMS boutique studios","Franchises","Premium personal trainers"],
      idealDe:["EMS-Boutique-Studios","Franchises","Premium-Personal-Trainer"],
      pitchEs:"20 minutos equivalen a 2 horas de entrenamiento. El modelo EMS tiene el ROI por m² más alto del sector &#8212; y Wiemspro domina el mercado.",
      pitchEn:"20 minutes equals 2 hours of training. The EMS model has the highest ROI per m² in the sector &#8212; and Wiemspro leads the market.",
      pitchDe:"20 Minuten entsprechen 2 Stunden Training. Das EMS-Modell hat den höchsten ROI pro m² der Branche.",
      products:[
        {ico:"◆",name:"Wiemspro Suit Pro",desc:"Traje EMS inalámbrico de nueva generación. Máxima libertad de movimiento."},
        {ico:"◆",name:"Wiemspro Control",desc:"Sistema de control centralizado para gestionar múltiples suits simultáneamente."},
        {ico:"◆",name:"Wiemspro Connect",desc:"App de seguimiento de rendimiento y planificación de entrenamientos EMS."},
      ],
      objEs:[{q:"'El EMS ya está muy explotado en mi ciudad'",a:"Wiemspro tiene la mayor tasa de retención del sector EMS (82%) precisamente porque el producto es superior. Más competencia = más necesidad del mejor."}],
      comboEs:"Wiemspro + Harbiz + Lemin = Centro EMS de alto rendimiento con gestión profesional",
    },
    {
      id:"olive", emoji:"·", tag:"Indoor Cycling",
      name:"O'live Fitness", tagline:"Premium indoor cycling redefined",
      taglineEs:"Ciclismo indoor premium redefinido",
      taglineDe:"Premium Indoor-Cycling neu definiert",
      descEs:"Línea premium de bicicletas de indoor cycling con diseño italiano y tecnología de alto rendimiento. La elección de los estudios de cycling más exclusivos del mundo.",
      descEn:"Premium indoor cycling bikes with Italian design and high-performance technology. The choice of the world's most exclusive cycling studios.",
      descDe:"Premium Indoor-Cycling-Fahrräder mit italienischem Design und Hochleistungstechnologie.",
      idealEs:["Estudios de cycling boutique","Gimnasios premium","Hoteles 5*"],
      idealEn:["Boutique cycling studios","Premium gyms","5* hotels"],
      idealDe:["Boutique-Cycling-Studios","Premium-Fitnessstudios","5*-Hotels"],
      pitchEs:"Cuando el espacio y el branding son parte del producto, O'live es la única opción que a la vez rinde y se ve increíble.",
      pitchEn:"When space and branding are part of the product, O'live is the only option that both performs and looks incredible.",
      pitchDe:"Wenn Raum und Branding Teil des Produkts sind, ist O'live die einzige Option.",
      products:[
        {ico:"◆",name:"O'live Bike Pro",desc:"Bicicleta de alto rendimiento con transmisión magnética silenciosa."},
        {ico:"◆",name:"O'live Connect",desc:"Pantalla integrada con clases en vivo y métricas en tiempo real."},
      ],
      objEs:[{q:"'Hay bicicletas más baratas en el mercado'",a:"Las bicicletas más baratas duran 3 años. O'live dura 10. El costo por año de vida útil es menor &#8212; y la experiencia del cliente es incomparable."}],
      comboEs:"O'live + SelfLoops + Mironova = Sala de cycling que compite con Peloton",
    },
    {
      id:"cube", emoji:"·", tag:"Functional Training",
      name:"CUBE Sports", tagline:"Modular functional training &#8212; German engineering",
      taglineEs:"Entrenamiento funcional modular &#8212; ingeniería alemana",
      taglineDe:"Modulares funktionales Training &#8212; Deutsche Ingenieurskunst",
      descEs:"Sistemas de entrenamiento funcional modulares y versátiles fabricados en Alemania. Adaptables a múltiples espacios, desde fisioterapia hasta entrenamiento funcional avanzado.",
      descEn:"Modular and versatile functional training systems made in Germany. Adaptable to multiple spaces, from physiotherapy to advanced functional training.",
      descDe:"Modulare und vielseitige Funktionstrainings-Systeme aus Deutschland.",
      idealEs:["Fisioterapia","Centros de rehabilitación","Gimnasios funcionales"],
      idealEn:["Physiotherapy","Rehabilitation centers","Functional gyms"],
      idealDe:["Physiotherapie","Rehabilitationszentren","Funktionelle Fitnessstudios"],
      pitchEs:"Fabricación alemana significa garantía, precisión y durabilidad que los clientes valoran. CUBE vende confianza además de equipamiento.",
      pitchEn:"German manufacturing means warranty, precision and durability that clients value. CUBE sells trust in addition to equipment.",
      pitchDe:"Deutsche Fertigung bedeutet Garantie, Präzision und Langlebigkeit.",
      products:[
        {ico:"◆",name:"CUBE Rig",desc:"Sistema de rig modular con más de 200 accesorios compatibles."},
        {ico:"◆",name:"CUBE Balance",desc:"Plataformas de equilibrio y propiocepción para rehabilitación."},
        {ico:"◆",name:"CUBE Wall",desc:"Sistema de pared multifuncional. Máximo uso del espacio vertical."},
      ],
      objEs:[{q:"'El presupuesto es limitado, prefiero algo más económico'",a:"CUBE tiene una gama entry que permite empezar con una inversión menor y ampliar modularmente. No es todo o nada."}],
      comboEs:"CUBE Sports + BASI + SelfLoops = Centro de fisioterapia y rehabilitación premium",
    },
    {
      id:"onnafit", emoji:"·", tag:"EMS Aesthetics",
      name:"Onnafit", tagline:"EMS body contouring &#8212; beauty meets fitness",
      taglineEs:"EMS body contouring &#8212; belleza y fitness juntos",
      taglineDe:"EMS Body Contouring &#8212; Schönheit trifft Fitness",
      descEs:"Sistema EMS especializado en estética corporal y contouring. Permite a salones de belleza y centros estéticos ofrecer servicios de alto valor con tecnología EMS.",
      descEn:"EMS system specialised in body aesthetics and contouring. Allows beauty salons and aesthetic centers to offer high-value services with EMS technology.",
      descDe:"EMS-System spezialisiert auf Körperästhetik und Konturierung.",
      idealEs:["Centros estéticos","Spas","Salones de belleza premium"],
      idealEn:["Aesthetic centers","Spas","Premium beauty salons"],
      idealDe:["Ästhetikzentren","Spas","Premium-Schönheitssalons"],
      pitchEs:"Onnafit abre el mercado estético al EMS &#8212; un mercado completamente diferente al fitness tradicional con ticket promedio mucho más alto.",
      pitchEn:"Onnafit opens the aesthetic market to EMS &#8212; a completely different market from traditional fitness with a much higher average ticket.",
      pitchDe:"Onnafit öffnet den ästhetischen Markt für EMS.",
      products:[
        {ico:"◆",name:"Onnafit Body Suit",desc:"Traje EMS optimizado para protocolos de body contouring."},
        {ico:"◆",name:"Onnafit Protocol",desc:"Protocolos de tratamiento certificados para diferentes objetivos estéticos."},
      ],
      objEs:[{q:"'Mis clientas no quieren entrenar, quieren tratamientos estéticos'",a:"Exactamente &#8212; Onnafit es un tratamiento estético, no una clase de fitness. No tienen que 'entrenar', solo relajarse y dejar que la tecnología trabaje."}],
      comboEs:"Onnafit + Sparkfield (sauna infrarrojo) + Harbiz = Centro de estética de alta gama",
    },
    {
      id:"poolbiking", emoji:"·", tag:"Aquatic Fitness",
      name:"POOLBIKING", tagline:"Aquatic cycling &#8212; joint-friendly high intensity",
      taglineEs:"Ciclismo acuático &#8212; alta intensidad sin impacto",
      taglineDe:"Aqua-Cycling &#8212; gelenkschonende Hochintensität",
      descEs:"Bicicletas especializadas para entrenamiento en piscina. Máxima intensidad cardiovascular con mínimo impacto articular. Nicho de alto crecimiento con muy poca competencia.",
      descEn:"Specialised bikes for pool training. Maximum cardiovascular intensity with minimal joint impact. High-growth niche with very little competition.",
      descDe:"Spezialisierte Fahrräder für das Training im Pool. Maximale kardiovaskuläre Intensität mit minimalem Gelenkstress.",
      idealEs:["Spas con piscina","Centros acuáticos","Hoteles resort"],
      idealEn:["Spas with pools","Aquatic centers","Resort hotels"],
      idealDe:["Spas mit Pool","Aquazentren","Resort-Hotels"],
      pitchEs:"Mercado de nicho = precios premium y prácticamente cero competencia directa. El primero que lo instala en su ciudad domina ese segmento.",
      pitchEn:"Niche market = premium prices and virtually zero direct competition. The first to install it in their city dominates that segment.",
      pitchDe:"Nischenmarkt = Premium-Preise und praktisch null direkte Konkurrenz.",
      products:[
        {ico:"◆",name:"POOLBIKING Aquabike",desc:"Bicicleta acuática de acero inoxidable. Resistencia al cloro certificada."},
        {ico:"◆",name:"POOLBIKING Connect",desc:"Sistema de audio subacuático para clases grupales inmersivas."},
      ],
      objEs:[{q:"'Tenemos piscina pero nunca hemos ofrecido clases de este tipo'",a:"Ese es exactamente el punto. POOLBIKING no necesita instructores especializados &#8212; los protocolos vienen incluidos. El espacio ya lo tienes."}],
      comboEs:"POOLBIKING + Sparkfield + Mironova = Experiencia wellness acuática única",
    },
    {
      id:"icaros", emoji:"·", tag:"VR Fitness",
      name:"ICAROS", tagline:"Virtual reality meets functional movement",
      taglineEs:"La realidad virtual se une al movimiento funcional",
      taglineDe:"Virtual Reality trifft funktionelle Bewegung",
      descEs:"Sistema de fitness en realidad virtual que combina gamificación con entrenamiento funcional real. Mejora el equilibrio, el core y la coordinación mientras el usuario vive una experiencia inmersiva.",
      descEn:"Virtual reality fitness system that combines gamification with real functional training. Improves balance, core and coordination while the user lives an immersive experience.",
      descDe:"Virtual-Reality-Fitness-System das Gamification mit echtem Funktionstraining kombiniert.",
      idealEs:["Centros de rehabilitación","Gimnasios premium","Centros de alto rendimiento"],
      idealEn:["Rehabilitation centers","Premium gyms","High-performance centers"],
      idealDe:["Rehabilitationszentren","Premium-Fitnessstudios","Hochleistungszentren"],
      pitchEs:"El WOW factor definitivo. Las personas entran por curiosidad y se quedan por la experiencia. Es el imán de captación más efectivo del mercado.",
      pitchEn:"The ultimate WOW factor. People come in out of curiosity and stay for the experience. It's the most effective acquisition magnet in the market.",
      pitchDe:"Der ultimative WOW-Faktor. Menschen kommen aus Neugier und bleiben wegen der Erfahrung.",
      products:[
        {ico:"◆",name:"ICAROS Orb",desc:"Plataforma de movimiento 360° con casco VR integrado."},
        {ico:"◆",name:"ICAROS Games",desc:"Biblioteca de experiencias y juegos terapéuticos y recreativos."},
        {ico:"◆",name:"ICAROS Medical",desc:"Versión certificada para rehabilitación neurológica y motora."},
      ],
      objEs:[{q:"'La realidad virtual es una moda'",a:"Los hospitales y centros de rehabilitación llevan 10 años usando VR con resultados clínicos probados. ICAROS Medical está certificado &#8212; no es entretenimiento, es terapia."}],
      comboEs:"ICAROS + Trackbar + Harbiz = Experiencia de entrenamiento sin igual",
    },
    {
      id:"sparkfield", emoji:"·", tag:"Adaptive Strength",
      name:"Sparkfield", tagline:"Guided adaptive strength &#8212; space-saving",
      taglineEs:"Fuerza adaptativa guiada &#8212; compacto y preciso",
      taglineDe:"Geführte adaptive Kraft &#8212; platzsparend und präzise",
      descEs:"Sistema de fuerza adaptativa guiada con control de carga por software. Compacto, preciso y con datos de rendimiento en tiempo real. Pensado para espacios reducidos de alto valor.",
      descEn:"Guided adaptive strength system with software-controlled load. Compact, precise and with real-time performance data. Designed for high-value compact spaces.",
      descDe:"Geführtes adaptives Kraftsystem mit softwaregesteuerter Last. Kompakt, präzise und mit Echtzeit-Leistungsdaten.",
      idealEs:["Wellness centers premium","Fisioterapia","Hoteles de lujo"],
      idealEn:["Premium wellness centers","Physiotherapy","Luxury hotels"],
      idealDe:["Premium-Wellness-Center","Physiotherapie","Luxushotels"],
      pitchEs:"Sparkfield redefine lo que se puede hacer en 15 metros cuadrados. Recovery y fuerza en un solo sistema que se ve como obra de arte.",
      pitchEn:"Sparkfield redefines what you can do in 15 square metres. Recovery and strength in one system that looks like a work of art.",
      pitchDe:"Sparkfield definiert neu, was man auf 15 Quadratmetern tun kann.",
      products:[
        {ico:"◆",name:"Sparkfield Pro",desc:"Máquina de fuerza con resistencia electromagnética adaptativa."},
        {ico:"◆",name:"Sparkfield Connect",desc:"Software de seguimiento de fuerza, progresión y recuperación."},
      ],
      objEs:[{q:"'Ya tenemos maquinaria de fuerza'",a:"Sparkfield no reemplaza tu sala de pesas &#8212; es el equipo premium de recuperación y fuerza guiada que va en el área VIP o el wellness floor que hoy no tienes."}],
      comboEs:"Sparkfield + Mindzmove + Harbiz = Wellness floor premium de alto ticket",
    },
    {
      id:"bodytone", emoji:"·", tag:"Full Gym Equipment",
      name:"Bodytone", tagline:"Professional gym equipment &#8212; 25 years · 80+ countries",
      taglineEs:"Equipamiento profesional &#8212; 25 años · 80+ países",
      taglineDe:"Professionelles Gym-Equipment &#8212; 25 Jahre · 80+ Länder",
      descEs:"Fabricante español con 25 años de experiencia, presente en más de 80 países. Línea completa de cardiovascular, musculación y ciclismo indoor con fabricación industrial propia y servicio llave en mano.",
      descEn:"Spanish manufacturer with 25 years of experience, present in more than 80 countries. Complete cardio, strength and indoor cycling line with its own industrial production and turnkey service.",
      descDe:"Spanischer Hersteller mit 25 Jahren Erfahrung, präsent in mehr als 80 Ländern. Komplette Kardio-, Kraft- und Indoor-Cycling-Linie.",
      idealEs:["Nuevos gimnasios","Centros municipales","Hoteles y hospitality","Cadenas en expansión"],
      idealEn:["New gyms","Municipal centers","Hotels & hospitality","Expanding chains"],
      idealDe:["Neue Fitnessstudios","Kommunale Zentren","Hotels & Hospitality","Expandierende Ketten"],
      pitchEs:"Bodytone es la única marca con la que puedes equipar un gimnasio completo, de cero, con un solo interlocutor, diseño 3D incluido y garantía industrial.",
      pitchEn:"Bodytone is the only brand with which you can equip a complete gym from scratch, with a single contact, 3D design included and industrial warranty.",
      pitchDe:"Bodytone ist die einzige Marke, mit der Sie ein komplettes Fitnessstudio von Grund auf ausstatten können.",
      products:[
        {ico:"◆",name:"Bodytone Cardio Line",desc:"Cintas, elípticas y bicis de alta gama con conectividad digital."},
        {ico:"◆",name:"Bodytone Strength Line",desc:"300+ máquinas de musculación. Desde selector de pesas hasta funcional."},
        {ico:"◆",name:"Bodytone Cycling",desc:"Bicicletas de spinning compatibles con plataformas de coaching digital."},
        {ico:"◆",name:"Bodytone 3D Design",desc:"Servicio de diseño 2D/3D del espacio antes de la instalación. Diferenciador único."},
        {ico:"◆",name:"Bodytone Turnkey",desc:"Desde consultoría hasta entrega e instalación. Un solo proveedor, cero fricción."},
      ],
      objEs:[
        {q:"'Ya tengo proveedores de equipamiento'",a:"Bodytone no pide que los reemplaces. Pide una oportunidad en el próximo proyecto. Con diseño 3D gratuito y servicio llave en mano, la propuesta se vende sola."},
        {q:"'Quiero marcas europeas reconocidas'",a:"Bodytone es la marca #1 en España y líder en Latinoamérica. Fabricación española con estándares europeos y presencia certificada en 80+ países."},
      ],
      comboEs:"Bodytone + Trackbar + Harbiz = Gimnasio completo digitalmente integrado desde día 1",
    },
  ],
  software:[
    {
      id:"rook", emoji:"·", tag:"Health Data API",
      name:"ROOK", tagline:"The health data layer for any app",
      taglineEs:"La capa de datos de salud para cualquier app",
      taglineDe:"Die Gesundheitsdaten-Schicht für jede App",
      descEs:"API que agrega datos de salud de wearables (Apple Watch, Garmin, Whoop, Oura…) y los conecta con cualquier aplicación. Infraestructura crítica para el ecosistema health-tech.",
      descEn:"API that aggregates health data from wearables (Apple Watch, Garmin, Whoop, Oura…) and connects them to any application. Critical infrastructure for the health-tech ecosystem.",
      descDe:"API die Gesundheitsdaten von Wearables aggregiert und mit jeder Anwendung verbindet.",
      idealEs:["Apps de salud y fitness","Compañías de seguros","Plataformas corporativas de bienestar"],
      idealEn:["Health & fitness apps","Insurance companies","Corporate wellness platforms"],
      idealDe:["Gesundheits- und Fitness-Apps","Versicherungsunternehmen","Corporate-Wellness-Plattformen"],
      pitchEs:"Si tienen una app y usuarios activos, necesitan ROOK. El argumento de venta se escribe solo: sin ROOK, sus datos de salud son islas.",
      pitchEn:"If they have an app and active users, they need ROOK. The sales argument writes itself: without ROOK, their health data are islands.",
      pitchDe:"Wenn sie eine App und aktive Nutzer haben, brauchen sie ROOK.",
      products:[
        {ico:"◆",name:"ROOK Connect API",desc:"Integración con 40+ fuentes de datos de salud y wearables."},
        {ico:"◆",name:"ROOK Analytics",desc:"Dashboard de datos de salud agregados para operadores."},
        {ico:"◆",name:"ROOK Enterprise",desc:"Solución para grandes corporaciones con gestión de datos de empleados."},
      ],
      objEs:[{q:"'Desarrollamos nuestra propia integración'",a:"ROOK te da 40 integraciones en semanas vs. 2 años de desarrollo. El costo de oportunidad de desarrollar in-house es enorme."}],
      comboEs:"ROOK + WizFit AI + Harbiz = El ecosistema de datos de salud más completo del mercado",
    },
    {
      id:"harbiz", emoji:"·", tag:"Studio Management SaaS",
      name:"Harbiz", tagline:"All-in-one SaaS for fitness professionals",
      taglineEs:"SaaS todo-en-uno para profesionales del fitness",
      taglineDe:"All-in-one SaaS für Fitness-Profis",
      descEs:"Plataforma SaaS que gestiona membresías, pagos, reservas, planes de entrenamiento y comunicación con clientes. Diseñada específicamente para PTs, fisioterapeutas y estudios boutique.",
      descEn:"SaaS platform that manages memberships, payments, bookings, training plans and client communication. Designed specifically for PTs, physiotherapists and boutique studios.",
      descDe:"SaaS-Plattform für Mitgliedschaften, Zahlungen, Buchungen, Trainingspläne und Kundenkommunikation.",
      idealEs:["Personal trainers","Fisioterapeutas","Estudios boutique","Pequeños y medianos gimnasios"],
      idealEn:["Personal trainers","Physiotherapists","Boutique studios","Small & medium gyms"],
      idealDe:["Personal Trainer","Physiotherapeuten","Boutique-Studios","Kleine und mittlere Fitnessstudios"],
      pitchEs:"Cada negocio fitness sin sistema eficiente pierde dinero cada día &#8212; en tiempo, en cobros perdidos, en clientes que no regresan. Harbiz lo resuelve en 48 horas.",
      pitchEn:"Every fitness business without an efficient system loses money every day &#8212; in time, missed payments, clients who don't return. Harbiz solves it in 48 hours.",
      pitchDe:"Jedes Fitnessunternehmen ohne effizientes System verliert täglich Geld.",
      products:[
        {ico:"◆",name:"Harbiz Booking",desc:"Sistema de reservas y gestión de calendario para clases y sesiones individuales."},
        {ico:"◆",name:"Harbiz Payments",desc:"Cobros automáticos, membresías y facturación integrada."},
        {ico:"◆",name:"Harbiz Training",desc:"Creación y envío de planes de entrenamiento personalizados."},
        {ico:"◆",name:"Harbiz App",desc:"App blanca con el branding del negocio para los clientes finales."},
      ],
      objEs:[{q:"'Ya usamos WhatsApp y Excel, nos funciona'",a:"Perfecto &#8212; eso significa que ya tienes la base. Harbiz hace lo mismo pero automatizado, cobrandote antes de que se olviden y con métricas reales de tu negocio."}],
      comboEs:"Harbiz + WizFit AI + ROOK = La plataforma de gestión más avanzada del sector",
    },
    {
      id:"wizfit", emoji:"·", tag:"AI Fitness Coaching",
      name:"WizFit AI", tagline:"AI personalisation at scale for studios",
      taglineEs:"Personalización IA a escala para estudios",
      taglineDe:"KI-Personalisierung in großem Maßstab",
      descEs:"Plataforma de coaching personalizado impulsada por IA que permite a entrenadores y estudios escalar la personalización sin escalar el equipo. Planes adaptativos, seguimiento automático.",
      descEn:"AI-powered personalised coaching platform that allows trainers and studios to scale personalisation without scaling the team. Adaptive plans, automatic tracking.",
      descDe:"KI-gestützte personalisierte Coaching-Plattform die es Trainern ermöglicht Personalisierung zu skalieren.",
      idealEs:["Personal trainers con múltiples clientes","Estudios con programas grupales","Apps de fitness"],
      idealEn:["PTs with multiple clients","Studios with group programs","Fitness apps"],
      idealDe:["PTs mit mehreren Kunden","Studios mit Gruppenprogrammen","Fitness-Apps"],
      pitchEs:"IA + fitness = el mercado que más crece en 2025. WizFit te posiciona como early mover antes de que sea mainstream.",
      pitchEn:"AI + fitness = the fastest growing market in 2025. WizFit positions you as an early mover before it goes mainstream.",
      pitchDe:"KI + Fitness = der am schnellsten wachsende Markt 2025.",
      products:[
        {ico:"◆",name:"WizFit AI Engine",desc:"Motor de IA que genera planes de entrenamiento adaptativos basados en datos del usuario."},
        {ico:"◆",name:"WizFit Dashboard",desc:"Panel del entrenador con vista de todos los clientes y alertas proactivas."},
      ],
      objEs:[{q:"'Mis clientes prefieren el trato personal, no la IA'",a:"WizFit no reemplaza al entrenador &#8212; lo potencia. El entrenador sigue siendo el héroe; la IA gestiona el 80% del trabajo administrativo para que pueda enfocarse en el 20% que importa."}],
      comboEs:"WizFit AI + Harbiz + ROOK = El stack tecnológico del PT del futuro",
    },
    {
      id:"selfloops", emoji:"·", tag:"Group Training Analytics",
      name:"SelfLoops", tagline:"Data-driven group training for studios",
      taglineEs:"Entrenamiento grupal basado en datos",
      taglineDe:"Datengetriebenes Gruppentraining",
      descEs:"Plataforma de entrenamiento grupal con analytics de rendimiento en tiempo real. Conecta wearables de los participantes y proyecta métricas durante la clase, motivando y gamificando.",
      descEn:"Group training platform with real-time performance analytics. Connects participants' wearables and projects metrics during the class, motivating and gamifying.",
      descDe:"Gruppentrainings-Plattform mit Echtzeit-Performance-Analytics.",
      idealEs:["Estudios de group fitness","CrossFit boxes","Centros con clases colectivas"],
      idealEn:["Group fitness studios","CrossFit boxes","Centers with group classes"],
      idealDe:["Group-Fitness-Studios","CrossFit-Boxen","Zentren mit Gruppenklassen"],
      pitchEs:"Los estudios con SelfLoops retienen un 35% más de miembros. La gamificación no es un gimmick &#8212; es retención.",
      pitchEn:"Studios with SelfLoops retain 35% more members. Gamification isn't a gimmick &#8212; it's retention.",
      pitchDe:"Studios mit SelfLoops behalten 35% mehr Mitglieder.",
      products:[
        {ico:"◆",name:"SelfLoops Live",desc:"Pantalla en sala con métricas en tiempo real de todos los participantes."},
        {ico:"◆",name:"SelfLoops Leaderboard",desc:"Rankings y desafíos entre miembros que impulsan la asistencia."},
        {ico:"◆",name:"SelfLoops Reports",desc:"Informes de rendimiento individuales y de clase para instructores."},
      ],
      objEs:[{q:"'Nuestros clientes no quieren que sus datos sean públicos'",a:"SelfLoops tiene modo privado donde cada miembro elige qué mostrar. La mayoría opta por el ranking una vez que prueban la motivación que genera."}],
      comboEs:"SelfLoops + O'live + Harbiz = El estudio de cycling más engagement de la ciudad",
    },
    {
      id:"amalgama", emoji:"·", tag:"Digital Consultancy",
      name:"Amalgama", tagline:"Digital transformation for health & wellness",
      taglineEs:"Transformación digital para salud y wellness",
      taglineDe:"Digitale Transformation für Gesundheit & Wellness",
      descEs:"Consultora digital especializada en el sector health-wellness. Desarrolla apps, webs y estrategias UX para empresas que quieren digitalizar su oferta.",
      descEn:"Digital consultancy specialised in the health-wellness sector. Develops apps, websites and UX strategies for companies that want to digitalise their offer.",
      descDe:"Digitale Unternehmensberatung spezialisiert auf den Health-Wellness-Sektor.",
      idealEs:["Cadenas fitness en transformación digital","Marcas de equipamiento con app","Startups health-tech"],
      idealEn:["Fitness chains in digital transformation","Equipment brands with app","Health-tech startups"],
      idealDe:["Fitnessketten in der digitalen Transformation","Equipment-Marken mit App","Health-Tech-Startups"],
      pitchEs:"El problema de transformación digital es universal en el sector. Amalgama es la solución que pocos conocen pero todos necesitan.",
      pitchEn:"The digital transformation problem is universal in the sector. Amalgama is the solution few know about but everyone needs.",
      pitchDe:"Das digitale Transformationsproblem ist universell im Sektor.",
      products:[
        {ico:"◆",name:"App Development",desc:"Desarrollo de apps nativas para iOS y Android para el sector fitness."},
        {ico:"◆",name:"UX/UI Design",desc:"Diseño de experiencia de usuario especializado en health y wellness."},
        {ico:"◆",name:"Web & Platform",desc:"Plataformas web para venta, comunidad y gestión de contenidos."},
      ],
      objEs:[{q:"'Ya tenemos un equipo tech interno'",a:"Amalgama trabaja con equipos internos &#8212; no los reemplaza. Aporta la especialización en el sector que un equipo generalista no tiene."}],
      comboEs:"Amalgama + Harbiz + ROOK = Stack tecnológico completo para una cadena fitness",
    },
    {
      id:"shark", emoji:"·", tag:"SEO & Digital Marketing",
      name:"Shark Digital", tagline:"Fitness & wellness SEO/SEA &#8212; Vienna, 15 years",
      taglineEs:"SEO/SEA especializado en fitness &#8212; Viena, 15 años",
      taglineDe:"Fitness & Wellness SEO/SEA &#8212; Wien, 15 Jahre",
      descEs:"Agencia de marketing digital con 15 años de experiencia en Viena, especializada en el sector fitness y wellness. SEO, SEM, redes sociales y captación de leads para operadores fitness.",
      descEn:"Digital marketing agency with 15 years of experience in Vienna, specialised in the fitness and wellness sector. SEO, SEM, social media and lead generation for fitness operators.",
      descDe:"Digitale Marketingagentur mit 15 Jahren Erfahrung in Wien, spezialisiert auf Fitness und Wellness.",
      idealEs:["Gimnasios y estudios en DACH","Marcas fitness con presencia digital","Nuevas aperturas"],
      idealEn:["Gyms & studios in DACH","Fitness brands with digital presence","New openings"],
      idealDe:["Fitnessstudios in DACH","Fitness-Marken mit digitaler Präsenz","Neueröffnungen"],
      pitchEs:"Marketing genérico no funciona en fitness. Shark habla el idioma del sector y tiene los casos de éxito para demostrarlo.",
      pitchEn:"Generic marketing doesn't work in fitness. Shark speaks the sector's language and has the success cases to prove it.",
      pitchDe:"Generisches Marketing funktioniert im Fitness nicht. Shark spricht die Sprache der Branche.",
      products:[
        {ico:"◆",name:"Shark SEO Fitness",desc:"Posicionamiento orgánico especializado para gimnasios y centros fitness."},
        {ico:"◆",name:"Shark Paid Media",desc:"Gestión de Google Ads y Meta Ads con CPL optimizado para fitness."},
        {ico:"◆",name:"Shark Analytics",desc:"Reporting mensual de KPIs de negocio vinculados al marketing."},
      ],
      objEs:[{q:"'Ya tenemos agencia de marketing'",a:"Pregunta cuántos de sus clientes son gimnasios. Shark tiene 15 años de clientes solo en fitness &#8212; la diferencia en resultados es medible en semanas."}],
      comboEs:"Shark Digital + Harbiz + Amalgama = Motor de captación y retención digital completo",
    },
    {
      id:"lemin", emoji:"·", tag:"Leadership & Culture",
      name:"Lemin", tagline:"AI-powered leadership platform for fitness orgs",
      taglineEs:"Plataforma de liderazgo IA para organizaciones fitness",
      taglineDe:"KI-gestützte Führungsplattform für Fitness-Organisationen",
      descEs:"Plataforma de desarrollo de liderazgo y cultura organizacional con IA. Feedback 360°, nudging conductual y analytics de cultura para cadenas y franquicias fitness.",
      descEn:"AI-powered leadership development and organisational culture platform. 360° feedback, behavioural nudging and culture analytics for fitness chains and franchises.",
      descDe:"KI-gestützte Führungsentwicklungs- und Organisationskulturplattform.",
      idealEs:["Cadenas fitness con múltiples ubicaciones","Franquicias","Operadores con equipos grandes"],
      idealEn:["Multi-location fitness chains","Franchises","Operators with large teams"],
      idealDe:["Fitnessketten mit mehreren Standorten","Franchises","Betreiber mit großen Teams"],
      pitchEs:"Los mejores operadores fitness toman decisiones con datos de personas. Lemin convierte la cultura en un activo medible y mejorable.",
      pitchEn:"The best fitness operators make decisions with people data. Lemin turns culture into a measurable and improvable asset.",
      pitchDe:"Die besten Fitness-Betreiber treffen Entscheidungen mit Personendaten.",
      products:[
        {ico:"◆",name:"Lemin 360°",desc:"Feedback multidireccional entre equipos con análisis automático."},
        {ico:"◆",name:"Lemin Nudge",desc:"Motor de IA que sugiere micro-acciones para mejorar comportamientos."},
        {ico:"◆",name:"Lemin Culture Board",desc:"Dashboard de cultura organizacional para directivos."},
      ],
      objEs:[{q:"'Eso es para empresas grandes, no para gimnasios'",a:"Las cadenas de 5+ ubicaciones tienen exactamente los mismos problemas que las corporaciones: rotación de personal, inconsistencia de servicio, managers sin datos. Lemin les da lo mismo que a las Fortune 500."}],
      comboEs:"Lemin + Shark Digital + Harbiz = La cadena fitness más bien gestionada del mercado",
    },
  ],
  services:[
    {
      id:"mironova", emoji:"·", tag:"Interior Design",
      name:"Mironova Interior Design", tagline:"Fitness & wellness interiors &#8212; Berlin since 2014",
      taglineEs:"Interiores fitness y wellness &#8212; Berlín desde 2014",
      taglineDe:"Fitness & Wellness-Innenarchitektur &#8212; Berlin seit 2014",
      descEs:"Estudio de diseño de interiores con sede en Berlín especializado en espacios fitness, wellness y hospitalidad desde 2014. Concepto a construcción &#8212; transforma espacios en experiencias que venden.",
      descEn:"Berlin-based interior design studio specialised in fitness, wellness and hospitality spaces since 2014. Concept to construction &#8212; transforms spaces into experiences that sell.",
      descDe:"Berliner Innenarchitekturstudio spezialisiert auf Fitness-, Wellness- und Hospitality-Räume seit 2014.",
      idealEs:["Nuevas aperturas premium","Renovaciones de alto nivel","Hoteles wellness","Desarrolladores inmobiliarios"],
      idealEn:["Premium new openings","High-level renovations","Wellness hotels","Property developers"],
      idealDe:["Premium-Neueröffnungen","Hochwertige Renovierungen","Wellness-Hotels","Immobilienentwickler"],
      pitchEs:"El espacio vende antes que el equipamiento. Mironova crea espacios que enamoran desde la primera visita y se pagan solos en meses.",
      pitchEn:"The space sells before the equipment. Mironova creates spaces that clients fall in love with from the first visit and pay for themselves in months.",
      pitchDe:"Der Raum verkauft sich vor dem Equipment.",
      products:[
        {ico:"◆",name:"Concept Design",desc:"Desarrollo del concepto espacial y la identidad del espacio."},
        {ico:"◆",name:"Project Planning",desc:"Planimetría, selección de materiales y coordinación con constructores."},
        {ico:"◆",name:"Full Execution",desc:"Gestión completa del proyecto desde concepto hasta llaves en mano."},
        {ico:"◆",name:"Brand Integration",desc:"Integración del branding y la identidad visual en el espacio físico."},
      ],
      objEs:[{q:"'Ya tenemos arquitecto'",a:"Mironova no es un arquitecto generalista &#8212; es un especialista que ha diseñado más de 80 espacios fitness en Europa. La diferencia es que entiende el negocio, no solo el diseño."}],
      comboEs:"Mironova + Bodytone + Harbiz = Apertura de gimnasio premium de A a Z",
    },
    {
      id:"fuco", emoji:"·", tag:"Service Robotics",
      name:"FuCo Care Robotics", tagline:"Service robots for fitness, rehab & hospitality",
      taglineEs:"Robots de servicio para fitness, rehab y hospitalidad",
      taglineDe:"Serviceroboter für Fitness, Reha & Hospitality",
      descEs:"Soluciones robóticas de servicio para el sector salud, fitness y hospitalidad. Robots autónomos de limpieza de suelos, recepción, orientación y transporte de servicios.",
      descEn:"Service robotics solutions for the health, fitness and hospitality sector. Autonomous floor cleaning, reception, wayfinding and service transport robots.",
      descDe:"Service-Robotik-Lösungen für Gesundheit, Fitness und Hospitality.",
      idealEs:["Grandes gimnasios y spas","Hospitales y clínicas","Hoteles resort"],
      idealEn:["Large gyms & spas","Hospitals & clinics","Resort hotels"],
      idealDe:["Große Fitnessstudios & Spas","Krankenhäuser & Kliniken","Resort-Hotels"],
      pitchEs:"La robótica de servicio en salud no es el futuro &#8212; es el presente. Los early adopters tienen la ventaja de posicionamiento y los costos más bajos de toda la curva.",
      pitchEn:"Service robotics in health isn't the future &#8212; it's the present. Early adopters have the positioning advantage and the lowest costs on the entire curve.",
      pitchDe:"Service-Robotik im Gesundheitswesen ist nicht die Zukunft &#8212; es ist die Gegenwart.",
      products:[
        {ico:"◆",name:"FuCo Clean",desc:"Robot autónomo de limpieza de suelos para grandes superficies."},
        {ico:"◆",name:"FuCo Welcome",desc:"Robot de recepción y orientación con pantalla interactiva."},
        {ico:"◆",name:"FuCo Transport",desc:"Robot de transporte de equipamiento y materiales en instalaciones."},
      ],
      objEs:[{q:"'Los robots aún no están listos para entornos de salud'",a:"FuCo lleva 6 años operando en hospitales europeos. Los protocolos de seguridad son médicos, no de almacén. El argumento ya está superado."}],
      comboEs:"FuCo Care + Mironova + Harbiz = La instalación fitness más tecnológica de tu ciudad",
    },
  ],
};
